Sylius\Component\Addressing\Model\Address:
    exclusion_policy: ALL
    xml_root_name: address
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
        firstName:
            expose: true
            type: string
            groups: [Default, Detailed]
        lastName:
            expose: true
            type: string
            groups: [Default, Detailed]
        street:
            expose: true
            type: string
            groups: [Default, Detailed]
        city:
            expose: true
            type: string
            groups: [Default, Detailed]
        postcode:
            expose: true
            type: string
            groups: [Default, Detailed]
        phoneNumber:
            expose: true
            type: string
            groups: [Default, Detailed]
        countryCode:
            expose: true
            type: string
            groups: [Default, Detailed]
        provinceCode:
            expose: true
            type: string
            groups: [Default, Detailed]
        provinceName:
            expose: true
            type: string
            groups: [Default, Detailed]
