# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_addressing_province_create:
    pattern: /create
    defaults:
        _controller: sylius_addressing.controller.province:createAction
        _redirect: sylius_addressing_country_list

sylius_addressing_province_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius_addressing.controller.province:updateAction
        _redirect: sylius_addressing_country_list

sylius_addressing_province_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_addressing.controller.province:deleteAction
