# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_zone_list:
    path: /
    defaults:
        _controller: SyliusAddressingBundle:Zone:index

sylius_zone_create:
    path: /type_{type}/create
    defaults:
        _controller: sylius.controller.zone:createAction
        _factory: sylius.factory.zone

sylius_zone_update:
    path: /{id}/update
    defaults:
        _controller: sylius.controller.zone:updateAction

sylius_zone_delete:
    path: /{id}/delete
    defaults:
        _controller: sylius.controller.zone:deleteAction
